"""first revision

迁移 ID: 81342e7908a1
父迁移:
创建时间: 2024-07-14 19:43:04.645682

"""

from __future__ import annotations

from collections.abc import Sequence

revision: str = "81342e7908a1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ("ascension",)
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
