"""first revision

迁移 ID: 6bf5eefd0cbd
父迁移: 0cdb9777e97d
创建时间: 2025-01-22 19:22:54.513452

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "6bf5eefd0cbd"
down_revision: str | Sequence[str] | None = "0cdb9777e97d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backpack", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_bundle", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("is_equipped", sa.Boolean(), nullable=False))
        batch_op.drop_column("item_amount")
        batch_op.drop_column("item_type")
        batch_op.drop_column("bundle_item_amount")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("backpack", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("bundle_item_amount", sa.INTEGER(), nullable=False)
        )
        batch_op.add_column(sa.Column("item_type", sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column("item_amount", sa.INTEGER(), nullable=False))
        batch_op.drop_column("is_equipped")
        batch_op.drop_column("is_bundle")

    # ### end Alembic commands ###
